name: Next.js CI Workflow

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - id: build
        name: Build Project
        run: npm run build

      - id: test
        if: steps.build.outcome == 'success'
        name: Run Unit Tests with Coverage
        run: |
          npm install --save-dev jest jest-junit
          npm test -- --coverage --ci --reporters=default --reporters=jest-junit
        env:
          CI: true

      - id: coverage
        if: steps.test.outcome == 'success'
        name: Generate Coverage Report Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/lcov.info
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both

      - name: Upload Coverage Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
